name: anythingllm
services:
  anythingllm:
    ports:
      - 3200:3001
    cap_add:
      - SYS_ADMIN
    volumes:
      - ${STORAGE_DIR}:/app/server/storage
      - ${STORAGE_DIR}/.env:/app/server/.env
    environment:
      - STORAGE_DIR=${STORAGE_DIR}
    image: mintplexlabs/anythingllm
