version: "3.8"

services:
  lazylibrarian:
    image: linuxserver/lazylibrarian
    container_name: lazylibrarian
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/mods:lazylibrarian-ffmpeg
      # - DOCKER_MODS=linuxserver/calibre-web:calibre|linuxserver/mods:lazylibrarian-ffmpeg #optional
    volumes:
      - ${DOCKER_VOLUME_BASE}/lazylibrarian/config:/config
      - ${DOWNLOADS_DIR}:/downloads
      - ${DOWNLOADS_DIR}/completed/LazyLibrarian:/downloads/completed/LazyLibrarian
      - ${BOOKS_DIR}:/books
      - ${AUDIOBOOKS_DIR}:/audiobooks
      - ${DOCKER_VOLUME_BASE}/lazylibrarian/media:/media
    ports:
      - ${LAZYLIBRARIAN_PORT}:5299
    restart: unless-stopped
