name: vscode
services:
    codeserver:
        container_name: vscodeserver
        ports:
            - 5100:8443
        environment:
            - PUID=1026
            - PGID=100
            - TZ=Europe/Berlin
            - PASSWORD=CHANGEME
            - DEFAULT_WORKSPACE=/repos
        volumes:
            - /volume1/docker/codeserver:/config
            - /volume1/docker/codeserver/data:/data
            - /volume1/docker:/repos
        restart: unless-stopped
        image: lscr.io/linuxserver/code-server:latest
