name: vscode
services:
    codeserver:
        container_name: vscodeserver
        ports:
            - 8377:8443
        environment:
            - PUID=1026
            - PGID=100
            - TZ=Europe/Berlin
            - PASSWORD=CHANGME
            - PROXY_DOMAIN=code.MYDOMAIN.com
            - SUDO_PASSWORD=CHANGEME
        volumes:
            - /volume1/docker/codeserver:/config
        restart: unless-stopped
        image: \