version: "3.8"
services:
        calibre:
                image: linuxserver/calibre
                container_name: calibre
                environment:
                        - PUID=${PUID}
                        - PGID=${PGID}
                        - TZ=${TZ}
                        - PASSWORD=${CALIBRE_PASSWORD}
                        # - CLI_ARGS= #optional
                volumes:
                        - ${DOCKER_VOLUME_BASE}/calibre/config:/config
                        - ${BOOKS_DIR}:/books
                ports:
                        - 7080:8080
                        - 7081:8081
                restart: unless-stopped
