volumes:
  grav-data:
    driver: local
    driver_opts:
      type: none
      device: $PWD/grav
      o: bind

services:
  grav:
    build: ./
    ports:
      - 6666:80
    volumes:
      - /volume1/docker/grav:/var/www/html